# Generated by Django 3.1.3 on 2020-12-09 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=10, verbose_name='昵称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmodels', models.CharField(max_length=20, verbose_name='规格')),
                ('nums', models.PositiveIntegerField(verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmodels', models.CharField(max_length=20, verbose_name='规格')),
                ('nums', models.PositiveIntegerField(max_length=50, verbose_name='进货数量')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进货时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmodels', models.CharField(max_length=15, verbose_name='规格')),
                ('nums', models.PositiveIntegerField(verbose_name='数量')),
                ('state', models.CharField(choices=[('state_1', '欠桶'), ('state_2', '压桶'), ('state_3', '还桶')], default='state_1', max_length=10, verbose_name='状态')),
                ('money', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='押金')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsystem.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单时间')),
                ('wmodels', models.CharField(max_length=20, verbose_name='规格')),
                ('nums', models.PositiveIntegerField(verbose_name='数量')),
                ('money', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='金额')),
                ('paymodels', models.CharField(choices=[('pay', '支付宝'), ('wechat', '微信'), ('now', '货到付款')], default='now', max_length=10, verbose_name='支付方式')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsystem.customertable')),
            ],
        ),
    ]
